### PR TITLE
🍎Fix weird behavior when enabling shiny tray control

### PR DESCRIPTION
**Pull request by mingjun97**
* Disabled shiny tray control option when outside MacOS
* Add check while enabling shiny tray control
* Fix the font size and layout of tray control to make it looks better
* Refine the right-click PopupMenu when enabling shiny tray control
* Mitigate memory leakage by reusing canvas for tray control instead of creating a new canvas every time.
* Support Dark/Light mode in MacOS tray control
* Replace control icon used in tray control to svg format to provide better quality.
----

Refined tray control (Fit the style of original system style):

**Switch in Settings**

image

**Dark Mode**
image
Compare with system component(Right)

**Light Mode**
image
Compare with system component(Right)

----
Fix Right-Click PopupMenu while enabling tray control:
image

----
**Know issue**
Tray control looks a little blur while enabling HIDPI(especially in built-in retina display).

### CODE REVIEW

**Comment by mingjun97** [comment]
Upload a release version for MacOS
https://github.com/mingjun97/ytmdesktop/releases/tag/v1.2.1

**Comment by rickinbsb** [comment]
Hey @mingjun97 you can check this out for emoji reference in latter commits https://gitmoji.carloscuesta.me/

**Comment by rickinbsb** [comment]
great work on this PR btw

**Comment by mingjun97** [comment]
> Hey @mingjun97 you can check this out for emoji reference in latter commits https://gitmoji.carloscuesta.me/

Thanks for reminding. I didn't know that before. :)

**Comment by adlerluiz** [comment]
Hello @mingjun97 

I'm very happy for your contributions with the YTMDesktop App, I've set up a group on discord so we can discuss about, are you interested? follows the invitation link https://discord.gg/PMwtUQ

**Pull request merged**
