### PR TITLE
Add Language for Korean :)

### PR DESCRIPTION
**Pull request by tbvjaos510**
Add ko.json and fix some typing in en.json
I didn't understand `LABEL_SETTINGS_TAB_GENERAL_CONTINUE_WHERE_LEFT_OF` and `LABEL_SETTINGS_TAB_GENERAL_SHINY_TRAY_DARK`
If you let me know, I'll re pull request

Thank you for creating this app!

### CODE REVIEW

**Comment by adlerluiz** [comment]
hi @tbvjaos510 

```LABEL_SETTINGS_TAB_GENERAL_CONTINUE_WHERE_LEFT_OF``` works as follows, if you are in your library and close the app, when you open it again, it will load your library, otherwise it would load the main page, in short, it continues from the page where you were before closing the app

```LABEL_SETTINGS_TAB_GENERAL_SHINY_TRAY_DARK``` according to the following PR - https://github.com/adlerluiz/ytmdesktop/pull/5 - if your MAC is on dark mode then check this

**Comment by tbvjaos510** [comment]
Thanks. Finish Translate!

**Comment by tbvjaos510** [comment]
I wonder how a login session when a program reload. May I ask?

**Comment by adlerluiz** [comment]
All settings are saved on config.json file on root app, and the user session is managed from electron default session on browser-window --> webPreferences - https://electronjs.org/docs/api/browser-window

**Pull request merged**
